proyecto/config/routes.rb
Rails.application.routes.draw do

  resources :empresas

  resources :asiento_detalles

  resources :asientos_contables

  resources :novedades_transitorias

  resources :periodos_de_pago do
    collection do
      post 'liquidar'
      get 'liquidar'
      get 'generar_recibos'
      post 'generar_recibos'
    end
    collection do
      get 'finalizar'
      get 'download'
    end
  end

  devise_for :users, :controllers => {:sessions => "custom_sessions"}

  resources :recibo_detalles

  resources :recibo_de_sueldos

  resources :salarios_basicos_historico

  resources :liquidacion_detalles

  resources :conceptos

  resources :liquidaciones do
    collection do
      post 'generar_recibo'
      post 'agregar_conceptos_fijos'
      get 'generar_recibo'
      get 'agregar_conceptos_fijos'
    end
  end

  resources :trabajadores

  resources :categorias

  resources :nacionalidades

  resources :log_auditorias

  resources :users

  resources :roles

   root to: 'pantalla_inicial#index'

end

proyecto/app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :timeoutable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def permisos_array
    @permisos = []
    self.role.permissions.find_each do |permisos|
      if permisos.actions.include?('read') or permisos.actions.include?('manage')
        @permisos.push permisos.subject_class
      end
    end
    return @permisos
  end
end

proyecto/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource except: [:create]
  def index
    @users = User.all
  end

  # GET /categorias/1
  # GET /categorias/1.json
  def show
    #setHabilitar(true)
    @users = User.all
  end

  # GET /categorias/new
  def new

  end

  # GET /categorias/1/edit
  def edit
    @users = User.all
  end

  # POST /categorias
  # POST /categorias.json
  def create

  end

  # PATCH/PUT /categorias/1
  # PATCH/PUT /categorias/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        LogAutitoria.create(user_name: current_user.email, role: current_user.role.name, action: "Modificar", table: "Usuario", registro: @user.id, tiempo: Time.now)
        format.html { redirect_to @user, notice: 'EL usuario ha sido actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @user}
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categorias/1
  # DELETE /categorias/1.json
  def destroy

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:role_id)
  end
end

proyecto/app/helpers/users_helper.rb
module UsersHelper
end

proyecto/app/views/users/_form.html.erb
<%= form_for @user, :validate => true, :html => { :id => 'validates'} do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="row">
      <div class="panel panel-default col-md-7">
        <br> <div class="field">
        <div class="col-md-6">
          <label for="ejemplo_email_3" class="control-label">Correo: </label>
          <%= @user.email %>
        </div>

        <div class="col-md-6">
          <label for="ejemplo_email_3" class="control-label">Rol<font color=#D00>*</font></label>
          <%=f.collection_select(:role_id, Role.all.order(name: :asc),
                                 :id, :name)%>
        </div>

      </div>
      </div>
    </div>
    <div class="field">
      <%= f.button(type: "submit", class: "btn btn-primary btn-circle btn-lg") do %>
          <i class="fa fa-save"></i>
      <% end %>
      <%= link_to '<i class="fa fa-reply"></i>'.html_safe, users_path, class: 'btn btn-success btn-circle btn-lg' %>
    </div>

<% end %>

<script>
    $('#validates').validetta({
        realTime : true
    });
</script>

proyecto/app/views/users/_users.html.erb
<div class="row">
  <br>
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Usuarios
      </div>
      <div class="panel-body">
        <table id="categoria" class="display" cellpadding="0" cellspacing="0" border="0" class="table table-condensed">
          <thead>
          <tr>
            <th>Correo</th>
            <th>Rol</th>
            <th>Acciones</th>
          </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
              <tr>
                <td><%= user.email%></td>

                <td><%= user.role.name %></td>
                <td><%= link_to '<i class="fa fa-eye"></i>'.html_safe, user, class: 'btn btn-success btn-circle'%>
                  <% if can? :update, user %>
                      <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_user_path(user), class: 'btn btn-warning btn-circle'%></td>
                  <% end %>
                  </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<head><script>
    $('#categoria').DataTable({
        "language": {
            "sProcessing":    "Procesando...",
            "sLengthMenu":    "Mostrar _MENU_ registros",
            "sZeroRecords":   "No se encontraron resultados",
            "sEmptyTable":    "Ningún dato disponible en esta tabla",
            "sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
            "sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
            "sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
            "sInfoPostFix":   "",
            "sSearch":        "Buscar:",
            "sUrl":           "",
            "sInfoThousands":  ",",
            "sLoadingRecords": "Cargando...",
            "oPaginate": {
                "sFirst":    "Primero",
                "sLast":    "Último",
                "sNext":    "Siguiente",
                "sPrevious": "Anterior"
            },
            "oAria": {
                "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
            }
        }
    });
</script></head>

proyecto/app/views/users/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Editar Usuario</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>
<%= render 'form' %>

<%= render 'users' %>

proyecto/app/views/users/index.html.erb

<%=  render 'users' %>

proyecto/app/views/users/show.html.erb

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Usuarios</h1>
  </div>
  <!-- /.col-lg-12 -->
</div>

<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this User from being saved:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <form class="form-horizontal" role="form">
      <div class="panel panel-default col-md-12">
        <br> <div class="form-group">
        <div class="col-md-4">
          <label for="ejemplo_email_3" class="control-label">Correo: </label>
          <%= @user.email %>
        </div>

        <div class="col-md-6">
          <label for="ejemplo_email_3" class="control-label">Rol: </label>
          <%= @user.role.name %>
        </div>

      </div>
        <br>
      </div>
      <div class="form-group">
        <br><br><br><br>
        <% if can? :update, @user %>
            <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_user_path(@user), class: 'btn btn-warning btn-circle btn-lg'%>
        <% end %>
        <%= link_to '<i class="fa fa-reply"></i>'.html_safe, users_path, class: 'btn btn-success btn-circle btn-lg' %>
      </div>
<% end %>
<%= render 'users' %>
</form>