proyecto/config/routes.rb
Rails.application.routes.draw do

  resources :empresas

  resources :asiento_detalles

  resources :asientos_contables

  resources :novedades_transitorias

  resources :periodos_de_pago do
    collection do
      post 'liquidar'
      get 'liquidar'
      get 'generar_recibos'
      post 'generar_recibos'
    end
    collection do
      get 'finalizar'
      get 'download'
    end
  end

  devise_for :users, :controllers => {:sessions => "custom_sessions"}

  resources :recibo_detalles

  resources :recibo_de_sueldos

  resources :salarios_basicos_historico

  resources :liquidacion_detalles

  resources :conceptos

  resources :liquidaciones do
    collection do
      post 'generar_recibo'
      post 'agregar_conceptos_fijos'
      get 'generar_recibo'
      get 'agregar_conceptos_fijos'
    end
  end

  resources :trabajadores

  resources :categorias

  resources :nacionalidades

  resources :log_auditorias

  resources :users

  resources :roles

   root to: 'pantalla_inicial#index'

end

proyecto/app/controllers/novedades_transitorias_controller.rb
class NovedadesTransitoriasController < ApplicationController
  before_action :set_novedad_transitoria, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  respond_to :html

  def index
    @novedades_transitorias = NovedadTransitoria.all
    respond_with(@novedades_transitorias)
  end

  def show
    respond_with(@novedad_transitoria)
  end

  def new
    @novedad_transitoria = NovedadTransitoria.new
  end

  def edit
  end

  def create
    #@novedad_transitoria = NovedadTransitoria.new(novedad_transitoria_params)
    #@novedad_transitoria.save
    #respond_with(@novedad_transitoria)

    @novedad_transitoria = NovedadTransitoria.new(novedad_transitoria_params)

    respond_to do |format|
      if @novedad_transitoria.save
        LogAutitoria.create(user_name: current_user.email, role: current_user.role, action: "Crear", table: "Novedades Transitorias", registro: @novedad_transitoria.id, tiempo: Time.now, cambios: ["Liquidacion id: " + @novedad_transitoria.liquidacion_id.to_s, "Concepto id:" + @novedad_transitoria.concepto_id.to_s, "Cantidad: " + @novedad_transitoria.cantidad.to_s, "Suma: " + @novedad_transitoria.suma.to_s, "Descuento: " + @novedad_transitoria.descuento.to_s])
        format.html { redirect_to @novedad_transitoria, notice: 'Novedad transitoria was successfully created.' }
        format.json { render :show, status: :created, location: @novedad_transitoria }
      else
        format.html { render :new }
        format.json { render json: @novedad_transitoria.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    #@novedad_transitoria.update(novedad_transitoria_params)
    #respond_with(@novedad_transitoria)
    respond_to do |format|
      if @novedad_transitoria.update(liquidacion_detalle_params)
        format.html { redirect_to @novedad_transitoria, notice: 'Novedad transitoria was successfully updated.' }
        format.json { render :show, status: :ok, location: @novedad_transitoria }
      else
        format.html { render :edit }
        format.json { render json: @novedad_transitoria.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    #@novedad_transitoria.destroy
    #respond_with(@novedad_transitoria)
    LogAutitoria.create(user_name: current_user.email, role: current_user.role, action: "Eliminar", table: "Novedades Transitorias", registro: @novedad_transitoria.id, tiempo: Time.now, cambios: ["Liquidacion id: " + @novedad_transitoria.liquidacion_id.to_s, "Concepto id:" + @novedad_transitoria.concepto_id.to_s, "Cantidad: " + @novedad_transitoria.cantidad.to_s, "Suma: " + @novedad_transitoria.suma.to_s, "Descuento: " + @novedad_transitoria.descuento.to_s])
    @novedad_transitoria.destroy
    respond_to do |format|
      format.html { redirect_to liquidacion_detalles_url, notice: 'Novedad transitoria was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_novedad_transitoria
    @novedad_transitoria = NovedadTransitoria.find(params[:id])
  end

  def novedad_transitoria_params
    params.require(:novedad_transitoria).permit(:liquidacion_id, :concepto_id, :cantidad, :suma, :descuento)
  end
end

proyecto/app/helpers/novedades_transitorias_helper.rb
module NovedadesTransitoriasHelper
end

proyecto/app/views/novedades_transitorias/_form.html.erb
<%= simple_form_for(@novedad_transitoria) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :liquidacion_id %>
    <%= f.input :concepto_id_integer %>
    <%= f.input :cantidad %>
    <%= f.input :suma %>
    <%= f.input :descuento %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

proyecto/app/views/novedades_transitorias/edit.html.erb
<h1>Editing novedad_transitoria</h1>

<%= render 'form' %>

<%= link_to 'Show', @novedad_transitoria %> |
<%= link_to 'Back', novedades_transitorias_path %>

proyecto/app/views/novedades_transitorias/index.html.erb
<h1>Listing novedades_transitorias</h1>

<table>
  <thead>
    <tr>
      <th>Liquidacion</th>
      <th>Concepto id integer</th>
      <th>Cantidad</th>
      <th>Suma</th>
      <th>Descuento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @novedades_transitorias.each do |novedad_transitoria| %>
      <tr>
        <td><%= novedad_transitoria.liquidacion_id %></td>
        <td><%= novedad_transitoria.concepto_id_integer %></td>
        <td><%= novedad_transitoria.cantidad %></td>
        <td><%= novedad_transitoria.suma %></td>
        <td><%= novedad_transitoria.descuento %></td>
        <td><%= link_to 'Show', novedad_transitoria %></td>
        <td><%= link_to 'Edit', edit_novedad_transitoria_path(novedad_transitoria) %></td>
        <td><%= link_to 'Destroy', novedad_transitoria, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Novedad transitoria', new_novedad_transitoria_path %>

proyecto/app/views/novedades_transitorias/new.html.erb
<h1>New novedad_transitoria</h1>

<%= render 'form' %>

<%= link_to 'Back', novedades_transitorias_path %>

proyecto/app/views/novedades_transitorias/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Liquidacion:</strong>
  <%= @novedad_transitoria.liquidacion_id %>
</p>

<p>
  <strong>Concepto id integer:</strong>
  <%= @novedad_transitoria.concepto_id_integer %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @novedad_transitoria.cantidad %>
</p>

<p>
  <strong>Suma:</strong>
  <%= @novedad_transitoria.suma %>
</p>

<p>
  <strong>Descuento:</strong>
  <%= @novedad_transitoria.descuento %>
</p>

<%= link_to 'Edit', edit_novedad_transitoria_path(@novedad_transitoria) %> |
<%= link_to 'Back', novedades_transitorias_path %>