proyecto/config/routes.rb
Rails.application.routes.draw do

  resources :empresas

  resources :asiento_detalles

  resources :asientos_contables

  resources :novedades_transitorias

  resources :periodos_de_pago do
    collection do
      post 'liquidar'
      get 'liquidar'
      get 'generar_recibos'
      post 'generar_recibos'
    end
    collection do
      get 'finalizar'
      get 'download'
    end
  end

  devise_for :users, :controllers => {:sessions => "custom_sessions"}

  resources :recibo_detalles

  resources :recibo_de_sueldos

  resources :salarios_basicos_historico

  resources :liquidacion_detalles

  resources :conceptos

  resources :liquidaciones do
    collection do
      post 'generar_recibo'
      post 'agregar_conceptos_fijos'
      get 'generar_recibo'
      get 'agregar_conceptos_fijos'
    end
  end

  resources :trabajadores

  resources :categorias

  resources :nacionalidades

  resources :log_auditorias

  resources :users

  resources :roles

   root to: 'pantalla_inicial#index'

end

proyecto/app/controllers/liquidaciones_controller.rb
class LiquidacionesController < ApplicationController
  before_action :set_liquidacion, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction

  before_filter :authenticate_user!
  load_and_authorize_resource except: [:create, :generar_recibo, :agregar_conceptos_fijos]
  # GET /liquidaciones
  # GET /liquidaciones.json
  def index
    @liquidaciones = Liquidacion.all
    @liquidacion = Liquidacion.new
    @inhabilitar = false
  end

  # GET /liquidaciones/1
  # GET /liquidaciones/1.json
  def show
    @liquidaciones = Liquidacion.all
  end

  # GET /liquidaciones/new
  def new
    @liquidacion = Liquidacion.new
    @liquidacion.liquidacion_detalles.build
  end

  # GET /liquidaciones/1/edit
  def edit
    @liquidaciones = Liquidacion.all
    @inhabilitar = true
  end

  # POST /liquidaciones
  # POST /liquidaciones.json
  def create
    @liquidacion = Liquidacion.new(liquidacion_params)
    @liquidacion.cargar_variables
    if Liquidacion.where(trabajador_id: @liquidacion.trabajador_id).where(periodo_de_pago_id: @liquidacion.periodo_de_pago_id).first == nil #liquidación del trabajador no fue creada para ese mes
      if @liquidacion.trabajador.estado == 'activo'
        #@liquidacion.update_attribute(:total, :total + @liquidacion.liquidacion_detalles - @liquidacion.liquidacion_detalles.descuento)
        respond_to do |format|
          if @liquidacion.save
            @total = 0
            LogAutitoria.create(user_name: current_user.email, role: current_user.role.name, action: "Crear", table: "Liquidaciones", registro: @liquidacion.id, tiempo: Time.now, cambios: ["Trabajador: " + @liquidacion.trabajador.nombre, "Periodo: " + @liquidacion.periodo_de_pago.mes_anho, "Fecha: " + Date.today.to_s, "Total: " + number_to_currency(@total, precision: 0, unit: "G.").to_s])
            format.html { redirect_to edit_liquidacion_path(@liquidacion), notice: 'La liquidación ha sido creada correctamente.'}
            format.json { render :show, status: :created, location: liquidaciones_path }
          else
            format.html { render :new }
            format.json { render json: @liquidacion.errors, status: :unprocessable_entity }
          end
        end
      else
        respond_to do |format|
          format.html { redirect_to liquidaciones_path, error: 'El trabajador ya no está activo.' }
          format.json { head :no_content }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to liquidaciones_path, error: 'La liquidación ya estaba creada.' }
        format.json { head :no_content }
      end
    end
  end

  # PATCH/PUT /liquidaciones/1
  # PATCH/PUT /liquidaciones/1.json
  def update
    $current_user = current_user
    if @liquidacion.periodo_de_pago.finalizado?
      respond_to do |format|
        format.html { redirect_to liquidaciones_path, error: 'No se puede editar la liquidación, el periodo ya está finalizado.' }
        format.json { render :show, status: :ok, location: liquidaciones_path }
      end
    else
      respond_to do |format|
        if @liquidacion.update(liquidacion_params)
          LogAutitoria.create(user_name: current_user.email, role: current_user.role.name, action: "Modificar", table: "Liquidaciones", registro: @liquidacion.id, tiempo: Time.now, cambios: ["Trabajador: " + @liquidacion.trabajador.nombre, "Periodo: " + @liquidacion.periodo_de_pago.mes_anho, "Fecha: " + @liquidacion.fecha_de_pago.to_s, "Total: " + number_to_currency(@liquidacion.total, precision: 0, unit: "G.").to_s])
          format.html { redirect_to @liquidacion, notice: 'La liquidación ha sido modificada correctamente.' + $AT.to_s }
          format.json { render :show, status: :ok, location: liquidaciones_path }
        else
          format.html { render :edit }
          format.json { render json: @liquidacion.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /liquidaciones/1
  # DELETE /liquidaciones/1.json
  def destroy
    @periodo_de_pago = PeriodoDePago.find(@liquidacion.periodo_de_pago_id)
    if @periodo_de_pago.finalizado == false
      LogAutitoria.create(user_name: current_user.email, role: current_user.role.name, action: "Eliminar", table: "Liquidaciones", registro: @liquidacion.id, tiempo: Time.now, cambios: ["Trabajador: " + @liquidacion.trabajador.nombre, "Periodo: " + @liquidacion.periodo_de_pago.mes_anho, "Fecha: " + @liquidacion.fecha_de_pago.to_s, "Total: " + number_to_currency(@liquidacion.total, precision: 0, unit: "G.").to_s])
      @liquidacion.destroy
      respond_to do |format|
        format.html { redirect_to liquidaciones_url, notice: 'La liquidación ha sido eliminada correctamente.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to liquidaciones_url, error: 'No se ha podido eliminar la liquidación, el periodo de pago ha finalizado.' }
        format.json { head :no_content }
      end
    end
  end

  def agregar_conceptos_fijos
    @liquidacion = Liquidacion.find(params[:id])
    Concepto.where(estado: "activo").order(codigo: :asc).fijo.each do |concepto|
      @ld = LiquidacionDetalle.create(liquidacion_id: @liquidacion.id, concepto_id: concepto.id, cantidad: 1, suma: 0, descuento: 0)
      LogAutitoria.create(user_name: current_user.email, role: current_user.role.name, action: "Crear", table: "Liquidacion_detalles", registro: @ld.id, tiempo: Time.now, cambios: ["Liquidacion_id: " + @liquidacion.id.to_s, "Concepto_id: " + concepto.id.to_s, "Cantidad: 1", "Suma: " + number_to_currency(@ld.suma, precision: 0, unit: "G.").to_s, "Descuento: " + number_to_currency(@ld.descuento, precision: 0, unit: "G.").to_s])
    end
    respond_to do |format|
        LogAutitoria.create(user_name: current_user.email, role: current_user.role.name, action: "Modificar", table: "Liquidaciones", registro: @liquidacion.id, tiempo: Time.now, cambios: ["Trabajador: " + @liquidacion.trabajador.nombre, "Periodo: " + @liquidacion.periodo_de_pago.mes_anho, "Fecha: " + @liquidacion.fecha_de_pago.to_s, "Total: " + number_to_currency(@liquidacion.total, precision: 0, unit: "G.").to_s])
        format.html { redirect_to @liquidacion, notice: 'La liquidación ha sido modificada correctamente.' + $AT.to_s }
        format.json { render :show, status: :ok, location: liquidaciones_path }
    end
  end

  def generar_recibo
    @liquidacion = Liquidacion.find(params[:id])
    pdf = Prawn::Document.new
    data = [["Código", "Nombre", "Cantidad", "Sumas", "Descuentos"]]
    @linea = pdf.cursor
    #pdf.image "ingenium.jpg", :width => 147, :height => 49
    pdf.image Rails.root.to_s + "/public" + Empresa.find(1).image_url.to_s, :width => 147, :height => 49
    @linea2 = pdf.cursor
    pdf.move_cursor_to(@linea)
    pdf.move_down 15
    pdf.font_size 7
    pdf.text "Solicitado por: " + current_user.email, :align => :right
    pdf.text Time.current.strftime("%d/%m/%Y %H:%M:%S"), :align => :right
    pdf.move_down 20
    pdf.text "Recibo de Liquidación de Salario", :align => :center, :size => 20
    pdf.move_down 12
    pdf.font_size 10
    @linea = pdf.cursor
    @sumas = 0
    @descuentos = 0
    pdf.text "Trabajador: " + @liquidacion.trabajador.nombre_apellido
    pdf.move_cursor_to(@linea)
    pdf.text "                                           " + "Categoría: " + @liquidacion.categoria.nombre + "                   Periodo: " + @liquidacion.periodo_de_pago.mes_anho, :align => :center
    pdf.move_cursor_to(@linea)
    pdf.text "Fecha: " + @liquidacion.fecha_de_pago.strftime("%d/%m/%Y"), :align => :right
    pdf.move_down 20
    pdf.text "Detalles", :align => :center, :size => 18
    @detalles_generales = Array.new
    @liquidacion.liquidacion_detalles.find_each do |detalle|

      @detalles_generales.push(detalle)
    end
    @liquidacion.novedades_transitorias.find_each do |nt|

      @detalles_generales.push(nt)
    end
    @detalles_generales.sort! { |a, b| a.concepto.codigo.to_s <=> b.concepto.codigo.to_s }
    @detalles_generales.each do |detalles|
      data += [[detalles.concepto.codigo, detalles.concepto.nombre, detalles.cantidad.to_s, number_to_currency(detalles.suma, precision: 0, unit: "G.").to_s, number_to_currency(detalles.descuento, precision: 0, unit: "G.").to_s]]
      @sumas = @sumas + detalles.suma
      @descuentos = @descuentos + detalles.descuento
    end
    pdf.table(data, :header => true, :column_widths => {0 => 100, 1 => 245}) do
      row(0).borders = [:bottom]
      row(0).border_width = 2
      row(0).font_style = :bold
    end
    pdf.move_down 10
    @linea = pdf.cursor
    pdf.text "Total Sumas:                       .", :align => :right
    pdf.move_cursor_to(@linea)
    pdf.text number_to_currency(@sumas, precision: 0, unit: "G.").to_s, :align => :right
    @linea = pdf.cursor
    pdf.text "Total Descuentos:                       .", :align => :right
    pdf.move_cursor_to(@linea)
    pdf.text number_to_currency(@descuentos, precision: 0, unit: "G.").to_s, :align => :right
    @linea = pdf.cursor
    pdf.text "Total Neto:                       .", :align => :right
    pdf.move_cursor_to(@linea)
    pdf.text number_to_currency(@liquidacion.total, precision: 0, unit: "G.").to_s, :align => :right
    pdf.move_down 30
    pdf.text "_______________________________", :align => :right
    pdf.text "Firma", :align => :right
    pdf.render_file "Recibo de sueldo.pdf"
    LogAutitoria.create(user_name: current_user.email, role: current_user.role.name, action: "Generar", table: "Recibo de salario", registro: @liquidacion.id, tiempo: Time.now)
    send_file 'Recibo de sueldo.pdf', :type=>"application/pdf", :x_sendfile=>true
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_liquidacion
    @liquidacion = Liquidacion.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def liquidacion_params

proyecto/app/helpers/liquidaciones_helper.rb
module LiquidacionesHelper
end

proyecto/app/views/liquidaciones/_conceptos_fijos_fields.html.erb
<div class="col-md-7">
  <big><%=f.collection_select(:concepto_id, Concepto.where('tipo_de_concepto' => 'fijo'),
                              :id, :codigo,
                              {:prompt => 'Seleccionar'})%></big>


</div>
<div class="col-md-3">
  <big><%= f.text_field :cantidad, :size => 2%></big>
</div>
<div class="col-md-2">
  <small><td><%= f.link_to_remove '<i class="fa fa-minus"></i>'.html_safe, class: 'btn btn-danger btn-circle' %></td></small>
</div>

proyecto/app/views/liquidaciones/_form.html.erb
<%= nested_form_for(@liquidacion, validate: true, :html => { :id => 'validates'}) do |f| %>
    <% if @liquidacion.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@liquidacion.errors.count, "error") %> prohibited this liquidacion from being saved:</h2>
          <ul>
            <% @liquidacion.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="row">
      <div class="panel panel-default col-md-12">
        <br>  <div class="form-group">
        <label for="ejemplo_email_3" class="col-md-1 control-label">Trabajador<font color=#D00>*</font></label>
        <div class="col-md-3">
          <%=f.collection_select(:trabajador_id , Trabajador.all,
                                 :id, :nombre_apellido, {:prompt => 'Seleccione un trabajador'},'data-validetta'=>'required')%>
          <!--<%= link_to '<i class="fa fa-plus"></i>'.html_safe, new_trabajador_path, remote: true, class: 'btn btn-warning btn-circle' %>-->

        </div>
        <!--<br>  <div class="form-group">
      <label for="ejemplo_email_3" class="col-md-2 control-label">Categoría</label>
      <div class="col-md-10">
        <%=f.collection_select(:categoria_id, Categoria.all,
                               :id, :nombre,
                               {:prompt => 'Seleccione la categoría del trabajador'})%>
      </div>
  </div>-->

        <div class="col-md-3">
          <label for="ejemplo_email_3" class="control-label">Periodo<font color=#D00>*</font></label>
          <%=f.collection_select(:periodo_de_pago_id, PeriodoDePago.where(finalizado: false),
                                 :id, :mes_anho,
                                 {:prompt => 'Seleccione un periodo'},'data-validetta'=>'required')%>
        </div>
        <!--<div class="col-md-5">
          <label for="ejemplo_email_3" class="control-label">Fecha de pago:</label>
          <%= f.text_field :fecha_de_pago, 'data-behaviour' => 'datepicker', :placeholder => "Seleccione la fecha",'data-validetta'=>'required', value: Date.today %>
        </div>-->
      </div>
        <% @periodo_de_pago = 0%>

        <!--<br>  <div class="form-group">
      <label for="ejemplo_email_3" class="col-md-2 control-label">Total</label>
      <div class="col-md-10">
    <%= f.text_field :total %>
      </div>
  </div>-->
        <br>
      </div>
      <div class="col-md-12">
        <div class="col-md-7">
          <div class="form-group">
            <div class="panel panel-default">
              <div class="panel-heading">
                <big><b>Novedades Transitorias</b></big>
              </div>

              <table id="liquidacion_detalles" class="display" cellspacing="0" width="100%">
                <tr>
                  <th>Concepto</th>
                  <th>Cantidad</th>
                  <th></th>
                </tr><!--, @liquidacion.novedades_transitorias.transitorias_ordenadas-->
                <%= f.fields_for :novedades_transitorias, :wrapper => false do |form| %>
                    <tr class="fields">
                          <td><%=form.collection_select(:concepto_id, Concepto.where(tipo_de_concepto: "variable", estado: "activo").order('codigo ASC'),
                                                        :id, :codigo_nombre,
                                                        {:prompt => 'Seleccionar'},'data-validetta'=>"required")%></td>
                          <td> <%= form.number_field :cantidad, :size => 2, 'data-validetta'=>"callback[sum],maxLength[9]" %></td>
                          <td><%= f.link_to_remove '<i class="fa fa-minus"></i>'.html_safe, class: 'btn btn-danger btn-circle' %></td>

                    </tr>
                <% end %>

              </table>

              <%= f.link_to_add '<i class="fa fa-plus"></i>'.html_safe, :novedades_transitorias, class: 'btn btn-success btn-circle', :data => { :target => "#liquidacion_detalles" } %>

            </div>
          </div>
        </div>
      </div>
    </div>
        <div class="form-group">
          <% if !@liquidacion.id.nil?%>
              <%= f.button(type: "submit", class: "btn btn-primary btn-circle btn-lg") do %>
                  <i class="fa fa-save"></i>
              <% end %>
              <%= link_to '<i class="fa fa-reply"></i>'.html_safe, liquidaciones_path, class: 'btn btn-success btn-circle btn-lg' %>
          <% else %>
              <%= f.button(type: "submit", class: "btn btn-primary") do %>
                  liquidar</i>
              <% end %>
              <%= link_to '<i class="fa fa-reply"></i>'.html_safe, root_path, class: 'btn btn-success btn-circle btn-lg' %>
          <% end %>
        </div>
<% end %>

<script>
    $(function() {
        var fieldsCount,
                maxFieldsCount = 4,
                $addLink = $('f.add_nested_fields');
        function toggleAddLink() {
            $addLink.toggle(fieldsCount <= maxFieldsCount)
        }
        $(document).on('nested:fieldAdded', function() {
            fieldsCount += 1;
            toggleAddLink();
        });
        $(document).on('nested:fieldRemoved', function() {
            fieldsCount -= 1;
            toggleAddLink();
        });
        // count existing nested fields after page was loaded
        fieldsCount = $('form .fields').length;
        toggleAddLink();
    })
</script>
<script type="text/javascript">
    $('.datepicker').datepicker()
    $('[data-behaviour~=datepicker]').datepicker({
        startDate: '-1d',
        endDate: '+1m'
    });
</script>
<script>
    $('#validates').validetta({
        validators: {
            callback: {
                sum: {
                    callback:  function( el, value ) {
                        if ( value >= 0 ){
                            return true
                        }
                        return false
                    },
                    errorMessage: "Debe ser mayor o igual a 0"
                }
            }
        },
        realTime : true
    });
</script>

proyecto/app/views/liquidaciones/_liquidacion_detalle_fields.html.erb
<div class="row">
<div class="col-md-6">
    <big><%=f.collection_select(:concepto_id, Concepto.where(tipo_de_concepto: "variable"),
                              :id, :codigo,
                              {:prompt => 'Seleccionar'},'data-validetta'=>"required")%></big>

</div>
<div class="col-md-5">
  <big><%= f.text_field :cantidad, :size => 2, 'data-validetta'=>"callback[sum],maxLength[9]"%></big>
</div>
<div class="col-md-1">
  <small><td><%= f.link_to_remove '<i class="fa fa-minus"></i>'.html_safe, class: 'btn btn-danger btn-circle' %></td></small>
</div>
</div>

<!--Concepto.where('tipo_de_concepto' => 'variable')-->

proyecto/app/views/liquidaciones/_novedad_transitoria_fields.html.erb
<div class="row">
<div class="col-md-6">
  <big><%=f.collection_select(:concepto_id, Concepto.where(tipo_de_concepto: "variable"),
                              :id, :codigo,
                              {:prompt => 'Seleccionar'}, 'data-validetta'=>"required")%></big>

</div>
<div class="col-md-5">
  <big><%= f.number_field :cantidad, :size => 2, 'data-validetta'=>"callback[sum],maxLength[9]"%></big>
</div>
<div class="col-md-1">
  <% if NovedadTransitoria.where(liquidacion_id: @liquidacion.id).first.nil? %>
    <small><td><%= f.link_to_remove '<i class="fa fa-minus"></i>'.html_safe, class: 'btn btn-danger btn-circle', disabled: @inhabilitar %></td></small>
  <% end %>
</div>
</div>

proyecto/app/views/liquidaciones/index.html.erb
<% if can? :create, @liquidacion %>
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Nueva Liquidación Individual</h1>
      </div>
      <!-- /.col-lg-12 -->
    </div>

    <%= render 'form' %>

    <div class="col-lg-12">
      <h1 class="page-header">Liquidar por Categoría</h1>
    </div>
    <%= form_tag(liquidar_periodos_de_pago_path) do %>
        <div class="panel panel-default col-md-12">
          <br>
          <div class="col-md-3">
            <label for="ejemplo_email_3" class="control-label">Periodo<font color=#D00>*</font></label>
            <%= select_tag(:id, options_from_collection_for_select(PeriodoDePago.where(finalizado: FALSE), "id", "mes_anho"), prompt: "Seleccione el periodo", 'data-validetta'=>'required',required: true) %>
          </div>
          <div class="col-md-3">
            <label for="ejemplo_email_3" class="col-md-4 control-label">Categoría<font color=#D00>*</font></label>
            <%= select_tag(:categoria_id, options_from_collection_for_select(Categoria.all, "id", "nombre"), prompt: "Todas las categorías") %>
          </div>
          <br><br>
        </div>
        <%= submit_tag(value="liquidar", class: 'btn btn-primary')%>
    <% end %>
<% end %>
<%= render 'liquidaciones' %>

proyecto/app/views/liquidaciones/index.js.erb
$("#liquidaciones").html("<%= escape_javascript(render("liquidaciones")) %>");

proyecto/app/views/liquidaciones/new.html.erb
<h1>Nueva liquidacion</h1>

<%= render 'form' %>

proyecto/app/views/liquidaciones/show.html.erb
<%= form_for(@liquidacion) do |f| %>
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Liquidación</h1>
      </div>
    </div>

    <form class="form-horizontal" role="form">
      <div class="panel panel-default">
        <br>  <div class="form-group">


        <% @trabajador = Trabajador.find(@liquidacion.trabajador_id) %>
        <% @categoria = Categoria.find(@liquidacion.categoria_id) %>
        <% @periodo_de_pago = PeriodoDePago.find(@liquidacion.periodo_de_pago_id)%>
        <% @total_sumas = 0 %>
        <% @total_descuentos = 0 %>
        <div class="col-md-3">
          <label for="ejemplo_email_3" class="control-label">Trabajador: </label>

          <%= @trabajador.nombre_apellido %>
        </div>

        <div class="col-md-3">
          <label for="ejemplo_email_3" class="control-label">Categoría: </label>

          <%= @categoria.nombre %>
        </div>


        <div class="col-md-3">
          <label for="ejemplo_email_3" class="control-label">Periodo: </label>
          <%= @periodo_de_pago.mes_anho %>
        </div>
        <div class="col-md-3">
          <label for="ejemplo_email_3" class="control-label">Fecha de proceso: </label>
          <%= @liquidacion.fecha_de_pago.strftime("%d/%m/%Y") %>
        </div>
      </div>
        <br>
      </div>
    </form>
    <h1 class="page-header"></h1>
    <div class="panel panel-default">
      <div class="panel-heading">
        Detalles
      </div>
      <div class="panel-body">
        <%= form_tag categorias_path, :method => 'get', :id => "categorias_search" do %>
            <p>
              <!--<%= label_tag "Mostrar: " %>
              <%= select_tag :per_page, options_for_select([2,4,8,12], params[:per_page].to_i),
                             :onchange => "if(this.value){window.location='?per_page='+this.value;}" %>
              <span class="pull-right">
                <%= text_field_tag :search, params[:search], :size => 14 %>
                <%= submit_tag "Buscar", :name => nil %>
              </span>-->
            </p>
            <table class="table table-striped table-bordered">
              <thead>
              <tr>
                <th>Concepto</th>
                <th>Nombre</th>
                <th>Cantidad</th>
                <th>Sumas</th>
                <th>Descuentos</th>
              </tr>
              </thead>
              <tbody>
              <% @detalles_generales = Array.new %>
              <% @liquidacion.liquidacion_detalles.each do |ld| %>
                  <% @detalles_generales.push(ld) %>
              <% end %>
              <% @liquidacion.novedades_transitorias.each do |nt| %>
                  <% @detalles_generales.push(nt) %>
              <% end %>
              <% @detalles_generales.sort! { |a, b| a.concepto.codigo.to_s <=> b.concepto.codigo.to_s } %>
              <% @detalles_generales.each do |detalles| %>
                  <td><%= detalles.concepto.codigo %></td>
                  <td><%= detalles.concepto.nombre %></td>
                  <td><%= detalles.cantidad %></td>
                  <td><%= number_to_currency(detalles.suma, precision: 0, unit: "G.") %></td>
                  <td><%= number_to_currency(detalles.descuento, precision: 0, unit: "G.") %></td>
                  <% @total_sumas = @total_sumas + detalles.suma %>
                  <% @total_descuentos = @total_descuentos + detalles.descuento %>
                  <tr/>
              <% end %>
              </tbody>
            </table>
              <div class="col-md-3 col-md-offset-9">
                <label for="ejemplo_email_3" class="control-label">Total Sumas:      </label><%= number_to_currency(@total_sumas, precision: 0, unit: "G.")%>
                <br>
                <label for="ejemplo_email_3" class="control-label">Total Descuentos: </label> <%= number_to_currency(@total_descuentos, precision: 0, unit: "G.") %>
                <br>
                <label for="ejemplo_email_3" class="control-label">Total Neto:       </label> <%= number_to_currency(@liquidacion.total, precision: 0, unit: "G.") %>
              </div>
            <p><p><p>
            </div>
            </div>
            <% if can? :update, @liquidacion %>
                <%= link_to '<i class="fa fa-pencil"></i>'.html_safe, edit_liquidacion_path(@liquidacion), class: 'btn btn-warning btn-circle btn-lg'%>
            <% end %>
            <%= link_to '<i class="fa fa-reply"></i>'.html_safe, liquidaciones_path, class: 'btn btn-success btn-circle btn-lg' %>
            <%= link_to "Generar Recibo", {:controller => "liquidaciones", :action => "generar_recibo", :id => @liquidacion.id }, class: 'btn btn-primary'%>
        <% end %>
<% end %>


</div>