proyecto/config/routes.rb
Rails.application.routes.draw do

  resources :empresas

  resources :asiento_detalles

  resources :asientos_contables

  resources :novedades_transitorias

  resources :periodos_de_pago do
    collection do
      post 'liquidar'
      get 'liquidar'
      get 'generar_recibos'
      post 'generar_recibos'
    end
    collection do
      get 'finalizar'
      get 'download'
    end
  end

  devise_for :users, :controllers => {:sessions => "custom_sessions"}

  resources :recibo_detalles

  resources :recibo_de_sueldos

  resources :salarios_basicos_historico

  resources :liquidacion_detalles

  resources :conceptos

  resources :liquidaciones do
    collection do
      post 'generar_recibo'
      post 'agregar_conceptos_fijos'
      get 'generar_recibo'
      get 'agregar_conceptos_fijos'
    end
  end

  resources :trabajadores

  resources :categorias

  resources :nacionalidades

  resources :log_auditorias

  resources :users

  resources :roles

   root to: 'pantalla_inicial#index'

end

proyecto/app/models/liquidacion_detalle.rb
class LiquidacionDetalle < ActiveRecord::Base
  belongs_to :liquidacion
  belongs_to :concepto
  before_create :calcular

  def calcular
    if self.concepto.suma_resta == "suma" then
      self.suma = $calculadora.evaluate(self.concepto.formula)*self.cantidad + self.concepto.monto*self.cantidad
    elsif self.concepto.suma_resta == "resta" then
      self.descuento = $calculadora.evaluate(self.concepto.formula)*self.cantidad + self.concepto.monto*self.cantidad
    end
    acumular
    Liquidacion.update(self.liquidacion_id, total: self.liquidacion.total + self.suma - self.descuento)
  end
  def acumular
    if self.concepto.acumuladores.include?("a1")
      $A1 = $A1 + self.suma + self.descuento
      $calculadora.store(a1: $A1)
    end
    if self.concepto.acumuladores.include?("a2")
      $A2 = $A2 + self.suma + self.descuento
      $calculadora.store(a2: $A2)
    end
    if self.concepto.acumuladores.include?("a3")
      $A3 = $A3 + self.suma + self.descuento
      $calculadora.store(a3: $A3)
    end
    if self.concepto.acumuladores.include?("a4")
      $A4 = $A4 + self.suma + self.descuento
      $calculadora.store(a4: $A4)
    end
    if self.concepto.acumuladores.include?("a5")
      $A5 = $A5 + self.suma + self.descuento
      $calculadora.store(a5: $A5)
    end
    if self.concepto.suma_resta == 'suma'
      $AT = $AT + self.suma + self.descuento
    else
      $AT = $AT - self.suma - self.descuento
    end
    $calculadora.store(at: $AT)
    @c = "c" + self.concepto.codigo
    $calculadora.store(@c => (self.descuento + self.suma))
  end
end

proyecto/app/controllers/liquidacion_detalles_controller.rb
class LiquidacionDetallesController < ApplicationController
  before_action :set_liquidacion_detalle, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  before_filter :authenticate_user!
  load_and_authorize_resource except: [:create]
  # GET /liquidacion_detalles
  # GET /liquidacion_detalles.json
  def index
    # @search = LiquidacionDetalle.search params[:search]
    # @order = @search.order :sort_column + " " + :sort_direction
    @liquidacion_detalles = LiquidacionDetalle.search(params[:search]).order(sort_column + ' ' + sort_direction).paginate(:per_page => 5, :page => params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @liquidacion_detalles }
    end
  end

  # GET /liquidacion_detalles/1
  # GET /liquidacion_detalles/1.json
  def show
  end

  # GET /liquidacion_detalles/new
  def new
    @liquidacion_detalle = LiquidacionDetalle.new
  end

  # GET /liquidacion_detalles/1/edit
  def edit
  end

  # POST /liquidacion_detalles
  # POST /liquidacion_detalles.json
  def create
    @liquidacion_detalle = LiquidacionDetalle.new(liquidacion_detalle_params)
    respond_to do |format|
      if @liquidacion_detalle.save
        LogAutitoria.create(user_name: current_user.email, role: current_user.role, action: "Crear", table: "Liquidacion_detalles", registro: @liquidacion_detalle.id)
        format.html { redirect_to @liquidacion_detalle, notice: 'Liquidacion detalle was successfully created.' }
        format.json { render :show, status: :created, location: @liquidacion_detalle }
      else
        format.html { render :new }
        format.json { render json: @liquidacion_detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /liquidacion_detalles/1
  # PATCH/PUT /liquidacion_detalles/1.json
  def update
    respond_to do |format|
      if @liquidacion_detalle.update(liquidacion_detalle_params)
        format.html { redirect_to @liquidacion_detalle, notice: 'Liquidacion detalle was successfully updated.' }
        format.json { render :show, status: :ok, location: @liquidacion_detalle }
      else
        format.html { render :edit }
        format.json { render json: @liquidacion_detalle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /liquidacion_detalles/1
  # DELETE /liquidacion_detalles/1.json
  def destroy
    @liquidacion_detalle.destroy
    respond_to do |format|
      format.html { redirect_to liquidacion_detalles_url, notice: 'Liquidacion detalle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_liquidacion_detalle
    @liquidacion_detalle = LiquidacionDetalle.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def liquidacion_detalle_params
    params.require(:liquidacion_detalle).permit(:liquidacion_id, :concepto_id, :cantidad, :suma, :descuento)
  end

  def sort_column
    LiquidacionDetalle.column_names.include?(params[:sort])? params[:sort] : 'cantidad'
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

proyecto/app/helpers/liquidacion_detalles_helper.rb
module LiquidacionDetallesHelper
end

proyecto/app/views/liquidacion_detalles/_form.html.erb
<%= form_for(@liquidacion_detalle, :validate => true) do |f| %>
  <% if @liquidacion_detalle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@liquidacion_detalle.errors.count, "error") %> prohibited this liquidacion_detalle from being saved:</h2>

      <ul>
      <% @liquidacion_detalle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <form class="form-horizontal" role="form">

      <br>  <div class="form-group">
      <label for="ejemplo_email_3" class="col-md-2 control-label">Liquidación ID</label>
      <div class="col-md-10">
    <%= f.number_field :liquidacion_id %>
      </div>
  </div>
      <br>  <div class="form-group">
      <label for="ejemplo_email_3" class="col-md-2 control-label">Concepto ID</label>
      <div class="col-md-10">
    <%= f.number_field :concepto_id %>
      </div>
  </div>
      <br>  <div class="form-group">
      <label for="ejemplo_email_3" class="col-md-2 control-label">Cantidad</label>
      <div class="col-md-10">
    <%= f.text_field :cantidad %>
      </div>
  </div>
      <br>  <div class="form-group">
      <label for="ejemplo_email_3" class="col-md-2 control-label">Suma</label>
      <div class="col-md-10">
    <%= f.text_field :suma %>
      </div>
  </div>
      <br>  <div class="form-group">
      <label for="ejemplo_email_3" class="col-md-2 control-label">Descuento</label>
      <div class="col-md-10">
    <%= f.text_field :descuento %>
      </div>
  </div>
      <br> <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <% if @liquidacion_detalle.id.nil?%>
            <%= f.submit('Crear') %>
        <% else %>
            <%= f.submit('Actualizar') %>
            <%= link_to 'Cancelar', liquidaciones_path%>
        <% end %>
      </div>
    </div>
<% end %>
</form>

proyecto/app/views/liquidacion_detalles/_liquidacion_detalles.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="pretty">
  <tr>
    <th><%= sortable "liquidacion_id","Liquidacion" %></th>
    <th><%= sortable "concepto_id","Concepto" %></th>
    <th><%= sortable "cantidad", "Cantidad" %></th>
  </tr>

  <% @liquidacion_detalles.each do |post| %>
      <tr>
        <td><%= post.liquidacion_id %></td>
        <td><%= post.concepto_id %></td>
        <td><%= post.cantidad %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_liquidacion_detalle_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>
<%= will_paginate @liquidacion_detalles %>

proyecto/app/views/liquidacion_detalles/edit.html.erb
<h1>Editar Liquidacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @liquidacion_detalle %> |
<%= link_to 'Back', liquidacion_detalles_path %>

proyecto/app/views/liquidacion_detalles/index.html.erb
<h1>Listing liquidacion_detalles</h1>

<%= form_tag liquidacion_detalles_path, :method => 'get', :id => "liquidacion_detalles_search" do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :concepto_id => nil %>
    </p>
    <div id="liquidacion_detalles"><%= render 'liquidacion_detalles' %></div>
<% end %>

<br>

<%= link_to image_tag('up_arrow.gif'), new_liquidacion_detalle_path %>

proyecto/app/views/liquidacion_detalles/index.js.erb
$("#liquidacion_detalles").html("<%= escape_javascript(render("liquidacion_detalles")) %>");

proyecto/app/views/liquidacion_detalles/new.html.erb
<h1>New liquidacion_detalle</h1>

<%= render 'form' %>

<%= link_to 'Back', liquidacion_detalles_path %>

proyecto/app/views/liquidacion_detalles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Liquidacion:</strong>
  <%= @liquidacion_detalle.liquidacion_id %>
</p>

<p>
  <strong>Concepto:</strong>
  <%= @liquidacion_detalle.concepto_id %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @liquidacion_detalle.cantidad %>
</p>

<p>
  <strong>Suma:</strong>
  <%= @liquidacion_detalle.suma %>
</p>

<p>
  <strong>Descuento:</strong>
  <%= @liquidacion_detalle.descuento %>
</p>

<%= link_to 'Edit', edit_liquidacion_detalle_path(@liquidacion_detalle) %> |
<%= link_to 'Back', liquidacion_detalles_path %>